---
-   name:   Echo from shell
    command: |
        echo "Environment vars"
        echo $DOCKER_IMAGE_PREFIX
        echo $IMAGE_NAME
    register: out_env
-   name: Output echo 3
    ansible.builtin.debug:
        var: out_env
-   name: Creates directory
    file:
        path: ~/k8s
        state: directory
-   name: Copy k8s definitions
    copy:
        src: ../../k8s/deployment.yml
        dest: ~/k8s/deployment.yml
-   name: Deploy blue env
    shell: |
        # echo "Env IMAGE_NAME"
        # echo $IMAGE_NAME
        cat ~/k8s/deployment/deployment.yml # | sed "s/{{IMAGE_NAME}}/$IMAGE_NAME/g"
    register: out
-   name: Output echo 3
    ansible.builtin.debug:
        var: out