---
-   name:   Echo from shell
    command: |
        echo "Environment vars"
        echo $DOCKER_IMAGE_PREFIX
        echo $IMAGE_NAME
    register: out_env
-   name: Output echo 3
    ansible.builtin.debug:
        var: out_env
-   name: Creates directory
    file:
        path: "{{ home_dir }}/k8s"
        state: directory
-   name: Copy k8s definitions
    copy:
        src: ../../k8s/deployment.yml
        dest: "{{ home_dir }}/k8s/deployment.yml"
-   name: Deploy blue env
    replace:
        path: "{{ home_dir }}/k8s/deployment.yml"
        regexp: '{{IMAGE_NAME}}'
        replace: $IMAGE_NAME
        backup: yes
    
    # register: out
    # shell: |
    #     sed s/IMAGE_NAME/$IMAGE_NAME/g {{ home_dir }}/k8s/deployment.yml >> {{ home_dir }}/transformed.txt
    #     # cat "{{ home_dir }}/k8s/deployment.yml" | sed s/IMAGE_NAME/$IMAGE_NAME/g >> {{ home_dir }}/transformed.txt
    #     # echo "test2 $IMAGE_NAME"
-   name: Output echo 3
    ansible.builtin.debug:
        var: out