apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-test-app-{{TARGET_ROLE}}
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      my-label: capstone-test-app-{{TARGET_ROLE}}
  template:
    metadata:
      labels:
        my-label: capstone-test-app-{{TARGET_ROLE}}
        my-role: {{TARGET_ROLE}}
    spec:
      containers:
      - name: capstone-test-app-container
        image: pkrzysztoff/capstone-test-app # tomcat:${TOMCAT_VERSION}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Blue Environment 2022-02-06"
---
        # ports:
        # - containerPort: 3000
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000