version: 2.1

commands:
  configure_constants:
    steps:
      - run:
          name: Configure constants
          command: |
            export IMAGE_NAME=pkrzysztoff/capstone-app-${CIRCLE_WORKFLOW_ID:0:7}
            export K8S_MASTER_NAME=Capstone K8s Master

  install_dotnet:
    steps:
      - run:
          name: Install .Net Core 6 SDK
          command: |
            sudo apt-get install wget
            wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo rm packages-microsoft-prod.deb
            sudo apt-get update; \
              sudo apt-get install -y apt-transport-https && \
              sudo apt-get update && \
              sudo apt-get install -y dotnet-sdk-6.0
  install_hadolint:
    steps:
      - run:
          name: Install hadolint
          command: |
            sudo apt-get install wget
            wget -O ~/hadolint https://github.com/hadolint/hadolint/releases/download/v2.8.0/hadolint-Linux-x86_64 &&\
              chmod +x ~/hadolint

executors:
  docker-builder:
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build-app:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - configure_constants
      - install_dotnet
      - run:
          name: Check dotnet
          command: dotnet --version
      - run:
          name: Build application
          command: |
            cd testapp
            dotnet restore
            dotnet build -c Release
            dotnet publish -c Release
            ls bin/Release/net6.0/publish
      - persist_to_workspace:
          root: ./
          paths:
            - testapp/bin/Release/net6.0/publish/

  lint-app:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - configure_constants
      - install_dotnet
      - install_hadolint
      - run:
          name: Lint application
          command: |
            ~/hadolint Dockerfile
            cd testapp
            dotnet format --verify-no-changes

  docker-build:
    executor: docker-builder
    steps:
      - checkout
      - configure_constants
      - attach_workspace:
          at: ./
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Save Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: ./
          paths: 
            - ./image.tar

  docker-publish:
    executor: docker-builder
    steps:
      - configure_constants
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load Docker image from workspace
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $IMAGE_NAME:latest
  
  deploy-app:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - configure_constants
      - run: apk -U upgrade
      - run:
          name: Install dependencies
          command: |
            apk add --update tar gzip
      - run:
          name: Install AWS Cli
          command: |
            apk add --no-cache --update python3 py3-pip 
            pip3 install --upgrade pip
            pip3 install --no-cache-dir awscli
            aws --version
      - run:
          name: Get master K8s node
          command: |
            export MASTER_IP=$(aws ec2 describe-instances --filters Name=tag:Name,Values=${K8S_MASTER_NAME} \
                                  --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
            echo "${MASTER_IP}"
            # echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
            # cat frontend/.env

workflows:
  default:
    jobs:
      - deploy-app

      # - build-app

      # - lint-app:
      #     requires: [build-app]

      # - docker-build:
      #     requires: [build-app]
      #     filters:
      #       branches:
      #         only: master
      ##     requires: [lint-app]
      # - docker-publish:
      #     requires: [docker-build]
      #     filters:
      #       branches:
      #         only: master