apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      my-label: capstone-app
  template:
    metadata:
      labels:
        my-label: capstone-app-___BUILD_ID___
        my-role: ___IMAGE_NAME___
    spec:
      containers:
      - name: capstone-test-app-container
        image: ___IMAGE_NAME___
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "___IMAGE_NAME___"
