apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-app
      environment: blue
  template:
    metadata:
      labels:
        app: capstone-app
        environment: blue
    spec:
      containers:
      - name: capstone-test-app-container
        image: ___IMAGE_NAME___
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Blue (___BUILD_ID___)"
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-app-blue-service
  namespace: default
  annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: capstone-app
    environment: blue
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002