apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-___BUILD_ID___-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-app
      version: ___BUILD_ID___
  template:
    metadata:
      labels:
        app: capstone-app
        version: ___BUILD_ID___
    spec:
      containers:
      - name: capstone-app-container
        image: ___IMAGE_NAME___
        env:
        - name: CAPSTONE_BUILD
          value: "___BUILD_ID___"
        - name: CAPSTONE_DEPLOY
          value: "___TIMESTAMP___"
