apiVersion: v1
kind: Service
metadata:
  name: capstone-app-green-service
  namespace: default
  annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: capstone-app
    environment: __TARGET__
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001