---
-   name: Creates directory
    file:
        path: "{{ home_dir }}/k8s"
        state: directory
-   name: Copy k8s green service definition
    copy:
        src: ../../k8s/green-service.yml
        dest: "{{ home_dir }}/k8s/green-service-to-blue-env.yml"
-   name: Copy k8s gray service definition
    copy:
        src: ../../k8s/gray-service.yml
        dest: "{{ home_dir }}/k8s/"
-   name: Blue env - update build id
    replace:
        path: "{{ home_dir }}/k8s/green-service-to-blue-env.yml"
        regexp: "___TARGET___"
        replace: "blue"
        backup: no
-   name: Green pre-deploy - move services
    shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        kubectl apply -f "{{ home_dir }}/k8s/green-service-to-blue-env.yml"
        kubectl apply -f "{{ home_dir }}/k8s/gray-service.yml"
    register: deploy_output
-   name: Deploy output
    ansible.builtin.debug:
        var: deploy_output
