apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-test-app-{{TARGET_ROLE}}
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      my-label: capstone-app-{{TARGET_ROLE}}
  template:
    metadata:
      labels:
        my-label: capstone-app-{{TARGET_ROLE}}
        my-role: {{TARGET_ROLE}}
    spec:
      containers:
      - name: capstone-test-app-container
        image: {{IMAGE_NAME}}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "{{TARGET_ROLE}}"
