---
-   name: Creates directory
    file:
        path: "{{ home_dir }}/k8s"
        state: directory
-   name: Copy k8s green service definition
    copy:
        src: ../../k8s/green-service.yml
        dest: "{{ home_dir }}/k8s/green-service-{{ lookup('env', 'BUILD_ID') }}.yml"
-   name: Green env service - update image name
    replace:
        path: "{{ home_dir }}/k8s/green-service-{{ lookup('env', 'BUILD_ID') }}.yml"
        regexp: "___IMAGE_NAME___"
        replace: "{{ lookup('env', 'IMAGE_NAME') }}"
        backup: no
-   name: Green env - promote new version
    shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        echo "Promote new version to prod: {{ lookup('env', 'BUILD_ID') }}"
        kubectl apply -f "{{ home_dir }}/k8s/green-service-{{ lookup('env', 'BUILD_ID') }}.yml"
    register: deploy_output
-   name: Deploy output
    ansible.builtin.debug:
        var: deploy_output
