---
-   name: Creates directory
    file:
        path: "{{ home_dir }}/k8s"
        state: directory
-   name: Copy k8s green deployment definition
    copy:
        src: ../../k8s/green-deployment.yml
        dest: "{{ home_dir }}/k8s/green-deployment-{{ lookup('env', 'BUILD_ID') }}.yml"
-   name: Green env - update image name
    replace:
        path: "{{ home_dir }}/k8s/green-deployment-{{ lookup('env', 'BUILD_ID') }}.yml"
        regexp: "___IMAGE_NAME___"
        replace: "{{ lookup('env', 'IMAGE_NAME') }}"
        backup: no
-   name: Green env - update build id
    replace:
        path: "{{ home_dir }}/k8s/green-deployment-{{ lookup('env', 'BUILD_ID') }}.yml"
        regexp: "___BUILD_ID___"
        replace: "{{ lookup('env', 'BUILD_ID') }}"
        backup: no
-   name: Green env - deploy application
    shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        echo "Deployment cmd: kubectl apply -f {{ home_dir }}/k8s/green-deployment-{{ lookup('env', 'BUILD_ID') }}.yml"
        kubectl delete -f "{{ home_dir }}/k8s/green-deployment-{{ lookup('env', 'BUILD_ID') }}.yml"
        kubectl create -f "{{ home_dir }}/k8s/green-deployment-{{ lookup('env', 'BUILD_ID') }}.yml"
    register: deploy_output
-   name: Deploy output
    ansible.builtin.debug:
        var: deploy_output
